---
user: www-data
group: www-data
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
port: 9393
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 4
threaded: true
daemonize: true